version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: accuflow
      POSTGRES_USER: accuflow
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ApexWeb2025!}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-public
    deploy:
      replicas: 1

  # Backend API
  backend:
    image: node:18-alpine
    working_dir: /app
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: accuflow
      DB_PASSWORD: ${DB_PASSWORD:-ApexWeb2025!}
      DB_NAME: accuflow
      JWT_SECRET: ${JWT_SECRET:-a8f5f167f44f4964e6c998dee827110c8c94f0b8e8c8e8f8e8c8e8f8e8c8e8f8}
      FRONTEND_URL: https://${FRONTEND_DOMAIN:-accounting.steinmetz.ltd}
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        apk add --no-cache python3 make g++ &&
        npm install &&
        npm run build &&
        sleep 10 &&
        npm start
      "
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN:-api.accounting.steinmetz.ltd}`)"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"

  # Frontend
  frontend:
    image: node:18-alpine
    working_dir: /app
    environment:
      VITE_API_URL: https://${BACKEND_DOMAIN:-api.accounting.steinmetz.ltd}
    volumes:
      - ./:/app
    command: >
      sh -c "
        npm install &&
        npm run build &&
        npx serve -s dist -l 3000
      "
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN:-accounting.steinmetz.ltd}`)"
        - "traefik.http.routers.frontend.tls=true"
        - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"

volumes:
  postgres_data:

networks:
  traefik-public:
    external: true